# Generated by Django 3.2 on 2021-04-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_api', '0002_rename_rapper_qacahce'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacahce',
            name='text_hash',
            field=models.CharField(default='_0', max_length=12),
        ),
        migrations.AlterField(
            model_name='qacahce',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
