# Generated by Django 3.2 on 2021-04-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_api', '0004_auto_20210422_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacahce',
            name='choices',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
