# Generated by Django 2.1.15 on 2021-04-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_api', '0005_qacahce_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qacahce',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
